[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build:packages",
  "NODE_OPTIONS=\"--max-old-space-size=6144\" npm run build:client"
]

[start]
cmd = "npm run backend"